name: P310-GPU
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.6.2
  - cudatoolkit=11.2.2
  - cudnn=8.1.0.77
  - libffi=3.4.4
  - openssl=3.0.13
  - pip=24.0
  - python=3.10.14
  - setuptools=69.5.1
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024a
  - vc=14.2
  - vs2015_runtime=14.29.30133
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - cachetools==5.3.3
      - certifi==2024.6.2
      - charset-normalizer==3.3.2
      - contourpy==1.2.1
      - cycler==0.12.1
      - flatbuffers==24.3.25
      - fonttools==4.53.0
      - gast==0.4.0
      - google-auth==2.30.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.64.1
      - h5py==3.11.0
      - idna==3.7
      - keras==2.10.0
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.5
      - libclang==18.1.1
      - markdown==3.6
      - markupsafe==2.1.5
      - matplotlib==3.9.0
      - numpy==1.26.4
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - packaging==24.1
      - pillow==10.3.0
      - protobuf==3.19.6
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - scipy==1.13.1
      - six==1.16.0
      - split-folders==0.5.1
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.10.1
      - tensorflow-estimator==2.10.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.4.0
      - typing-extensions==4.12.2
      - urllib3==2.2.1
      - werkzeug==3.0.3
      - wrapt==1.16.0
